[custom.all.posix]
type = "local"
path = "posix"
ipkg = "posix.ipkg"

[custom.all.linux]
type = "local"
path = "linux"
ipkg = "linux.ipkg"

[custom.all.linux-examples]
type = "local"
path = "."
ipkg = "examples/linux-examples.ipkg"

[custom.all.cptr]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-cptr"
commit = "latest:main"
ipkg   = "cptr.ipkg"

[custom.all.array]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-array"
commit = "latest:main"
ipkg   = "array.ipkg"

[custom.all.bytestring]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-bytestring"
commit = "latest:main"
ipkg   = "bytestring.ipkg"
